# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtra',
            new_name='Extra',
        ),
    ]
