# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_str', models.CharField(blank=True, default=1, max_length=500)),
                ('role', models.IntegerField(blank=True, default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtra',
        ),
    ]
