# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0002_auto_20160316_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='role',
            field=models.IntegerField(blank=True),
        ),
    ]
