# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0003_auto_20160316_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='permission_str',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='extra',
            name='role',
            field=models.IntegerField(blank=True, default=b''),
        ),
    ]
