# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0004_auto_20160316_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='role',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
