# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0005_auto_20160316_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='permission_str',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
    ]
